version: '3'
services:
  unite1:
    image: img_unite
    container_name: unite1
    restart: always
    hostname: "1"
    networks_on:
      -unite_network
  unite2:
    image: img_unite
    container_name: unite2
    restart: always
    hostname: "2"
    networks_on:
      -unite_network
  unite3:
    image: img_unite
    container_name: unite3
    restart: always
    hostname: "3"
    networks_on:
      -unite_network
  unite4:
    image: img_unite
    container_name: unite4
    restart: always
    hostname: "4"
    networks_on:
      -unite_network
  unite5:
    image: img_unite
    container_name: unite5
    restart: always
    hostname: "5"
    networks_on:
      -unite_network

  networks:
     usine_network:
        driver: bridge
        ipam:
        # driver: default
          config:
            - subnet: 172.17.0.1/16
             #    gateway: 172.30.0.1
            driver_opts:
              com.docker.network.bridge.name: dckr-ifc-usn